### PR TITLE
feat: playwright github action

### PR DESCRIPTION
**Pull request by tracy-french**
# Description

This change enables running `playwright` tests as a GitHub action.

Additionally, the `playwright.config.ts` includes an update to start the development server before running tests.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Build passed locally

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Legal

This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

### CODE REVIEW

**Comment by tracy-french** [comment]
Be sure to checkout the test run artifact at https://github.com/awslabs/iot-application/actions/runs/4474738764.

**Review by chejimmy — APPROVED** [review]
LGTM! 🙌

**Comment by chejimmy** [comment]
> Be sure to checkout the test run artifact at https://github.com/awslabs/iot-application/actions/runs/4474738764.

html looks great <3

Suggestion: Can we view the result without downloads? How about something like deploying the report html file to github static page ([example](https://dev.to/ysfaran/how-to-use-playwright-with-github-actions-and-github-pages-4gdl), [another](https://marcusfelling.com/blog/2021/publishing-playwright-test-results-to-github-pages/))?

**Comment by tracy-french** [comment]
> > Be sure to checkout the test run artifact at https://github.com/awslabs/iot-application/actions/runs/4474738764.
> 
> html looks great <3
> 
> Suggestion: Can we view the result without downloads? How about something like deploying the report html file to github static page ([example](https://dev.to/ysfaran/how-to-use-playwright-with-github-actions-and-github-pages-4gdl), [another](https://marcusfelling.com/blog/2021/publishing-playwright-test-results-to-github-pages/))?

That's a great idea! Thanks for the links! Do you know if we can deploy multiple items to GH pages? For example, docs and the playwright report?

**Pull request merged**
