### PR TITLE
feat: react-hook-form devtools exposed in production #1928

### PR DESCRIPTION
**Pull request by Priyanshu44**
Issue : https://github.com/awslabs/iot-application/issues/1928

Fix:
Added a flag to check production env and conditionally rendered devtool.

### CODE REVIEW

**Comment by Chandru-HM** [comment]
LGTM.

**Comment by tracy-french** [comment]
@Priyanshu44 Was this tested with a deployed app or with the env flag manually set to see the devtools go away?

**Comment by Priyanshu44** [comment]
> @Priyanshu44 Was this tested with a deployed app or with the env flag manually set to see the devtools go away?

Manually tested as we don't have access to deploy.

**Comment by tracy-french** [comment]
@Priyanshu44 Can you not follow https://github.com/awslabs/iot-application/tree/main/deploymentguide and deploy into your own AWS account?

**Review by tracy-french — APPROVED** [review]

**Comment by tracy-french** [comment]
I'm good to go ahead with the PR, as it looks safe. We will still need to confirm with a deployed version that this change was effective. I can take care of that.

**Pull request merged**
